sudo: false
language: cpp

compiler:
  - clang
before_install:
- git submodule update --init --recursive
install:
addons:
  apt:
    sources:
    - kalakris-cmake
    packages:
    - liblua5.2-dev
    - cmake
env:
  - BUILD_TYPE=Release CXX_FLAGS=-std=c++11 LUALIB=lua5.2

script:
  - cmake . -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DLUA_SEARCH_LIB_NAME=${LUALIB} && cmake --build . && CTEST_OUTPUT_ON_FAILURE=1 ctest

